# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy a new version to the fir.im"
  lane :fir_im do
    gradle(
      task: "assemble",
      build_type: "Release"
    )

    # Android version: app/build.gradle
    # android.defaultConfig

    # update to fir.im
    fir_cli(
      api_token: "",
      short: "anaelfbingodemo",
      changelog: "Hello aelf",
      dingtalk_access_token: "",
    )
  end

  desc "Push to telegram"
  lane :push_telegram do
    version_name = get_version_name(app_project_dir: '**/app')
    version = sh( "../../fastlane_version.sh");
    UI.message("final version: " + version + version_name )
    telegram(
      token: "",
      chat_id: "",
      text: "http://d.firim.vip/anaelfbingodemo " + "aelfBingoDevDemo-" + version_name + " Android Build" + version,
      proxy: "http://127.0.0.1:1087"
    )
  end

  desc "Final version"
  lane :get_version do
    push_telegram
  end
end
